POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo Evento 2",
    "details": "Sem descricao",
    "maximumAttendees": 2

}

###

POST http://localhost:3333/events/cd36eb33-7950-4a5d-abd9-4b8e85439600/attendees
Content-Type: application/json

{
    "name": "Lucas",
    "email": "lucas@gmail.com"
}

###
GET http://localhost:3333/events/cd36eb33-7950-4a5d-abd9-4b8e85439600

###

GET http://localhost:3333/attendees/10/badge

###
GET http://localhost:3333/attendees/10/check-in

###
GET http://localhost:3333/events/cd36eb33-7950-4a5d-abd9-4b8e85439600/attendees