POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo Evento",
    "details": "Sem descricao",
    "maximumAttendees": 1

}

###

POST http://localhost:3333/events/5a9a75b8-70d7-4dd3-a8f4-a3f1075afd38/attendees
Content-Type: application/json

{
    "name": "Lucas Ballonje",
    "email": "lucasballonje13@gmail.com"
}

###
GET http://localhost:3333/events/5a9a75b8-70d7-4dd3-a8f4-a3f1075afd38